### ISSUE TITLE
Can/Should we choose a better name for this?

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/router.js#2]
asking @gaand and @jrhorn424 please?

**Comment by gaand** [comment]
See ga-wdi-boston/ember#9

**Comment by gaand** [comment]
@J-Weeks Are we using router.js?

**Comment by gaand** [comment]
See ga-wdi-boston/django-backbone-project#2

Both repos should be renamed together (if we're using router.js).

**Comment by RealWeeks** [comment]
@jrhorn424 @jrhorn424 this has been renamed, please see referenced issue.
